{% set name = "gordias" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gordias-{{ version }}.tar.gz
  sha256: efa1721b46dce0a360bc514d3b76becf4761af0c1d272ff72a9cfcdca7bed8a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<3.12
    - setuptools >=64
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.10,<3.12
    - dask >=2023.1.0
    - dask-jobqueue
    - dask-mpi
    - distributed >=2023.1.0
    - netcdf4
    - numpy
    - pandas
    - psutil
    - scitools-iris >=3,<4

test:
  imports:
    - gordias
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.smhi.se/climix/gordias
  summary: A core project for climate data handling
  dev_url: https://git.smhi.se/climix/gordias
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nCarolina
    - ljoakim
